// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IReviewOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IReviewOracle";
  readonly sourceName: "contracts/interfaces/IReviewOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"_actionHash","type":"bytes32"}],"name":"flagActionForReview","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IReviewOracle.sol";
  readonly buildInfoId: "solc-0_8_28-d471feecf3977c7fa88b7b1f92f363bae2dbf572";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IReviewOracle"]: IReviewOracle$Type;
    ["contracts/interfaces/IReviewOracle.sol:IReviewOracle"]: IReviewOracle$Type;
  }
}