// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IActionRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IActionRegistry";
  readonly sourceName: "contracts/interfaces/IActionRegistry.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"_actionHash","type":"bytes32"}],"name":"getActionStatus","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IActionRegistry.sol";
  readonly buildInfoId: "solc-0_8_28-d471feecf3977c7fa88b7b1f92f363bae2dbf572";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IActionRegistry"]: IActionRegistry$Type;
    ["contracts/interfaces/IActionRegistry.sol:IActionRegistry"]: IActionRegistry$Type;
  }
}